### ISSUE TITLE
Issue with RPi Bullseye and/or newer version of Python

### ISSUE THREAD

**Issue by myervin** [linuxkidd/rvc-monitor-py#7]
Hey great work on this! Using the previous coachproxy RV-C versions on my Entegra, now excited to try adding support for NMEA2000 PGN's for the boat.

I'm not a Linux guy and I don't know Python (yet), so I'm kinda stuck, here are the details, thanks!:

pi@ervinosn2k:~ $ rvc2mqtt.py 
Connecting to CAN-Bus interface: can0
Traceback (most recent call last):
  File "/usr/bin/rvc2mqtt.py", line 295, in <module>
    bus = can.interface.Bus(channel=args.interface, bustype='socketcan_native')
  File "/usr/local/lib/python3.9/dist-packages/can/interface.py", line 101, in __new__
    kwargs = load_config(config=kwargs, context=context)
  File "/usr/local/lib/python3.9/dist-packages/can/util.py", line 192, in load_config
    bus_config = _create_bus_config(config)
  File "/usr/local/lib/python3.9/dist-packages/can/util.py", line 211, in _create_bus_config
    raise CanInterfaceNotImplementedError(
can.exceptions.CanInterfaceNotImplementedError: Unknown interface type "socketcan_native"

Changed line 296 socketcan_native to socketcan (as per this: https://issueantenna.com/repo/spanni26/pyhpsu/issues/52) and it gets past that but then hangs:

pi@ervinosn2k:/etc $ rvc2mqtt.py
Connecting to CAN-Bus interface: can0
Loading RVC Spec file /etc/rvc/rvc-spec.yml.
Processing start...

pi@ervinosn2k:~ $ python - version    
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 

Raspberry Pi 4B

pi@ervinosn2k:/proc/device-tree $ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye

**Comment by AshleyGrant** [comment]
@myervin I know it's been over two years, but were you ever able to resolve this issue?

**Comment by myervin** [comment]
Hi, yes I believe so. I forgot what the solution was tho. Couldn't have been too difficult...Thanks,Rob
-------- Original message --------From: Ashley Grant ***@***.***> Date: 12/27/24  1:14 PM  (GMT-06:00) To: linuxkidd/rvc-monitor-py ***@***.***> Cc: myervin ***@***.***>, Mention ***@***.***> Subject: Re: [linuxkidd/rvc-monitor-py] Issue with RPi Bullseye and/or newer version of Python (Issue #7) 
@myervin I know it's been over two years, but were you ever able to resolve this issue?
